stages:
  - deploy

sync_to_github:
  stage: deploy
  only:
    - main
  script:
    - git config --global user.name "GitLab CI"
    - git config --global user.email "ci@gitlab.com"

    # Add GitHub remote
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/lolikgiovi/adtools.git

    # Create a local branch that points to the current commit
    - git checkout -b main

    # Force push to GitHub main
    - git push github main --force
